# GNU Make project makefile autogenerated by Premake
ifndef config
  config=debug
endif

ifndef verbose
  SILENT = @
endif

ifndef CC
  CC = gcc
endif

ifndef CXX
  CXX = g++
endif

ifndef AR
  AR = ar
endif

ifeq ($(config),debug)
  OBJDIR     = obj/Debug
  TARGETDIR  = lib
  TARGET     = $(TARGETDIR)/liblzma.a
  DEFINES   += -DHAVE_CONFIG_H -DHAVE_STDBOOL_H
  INCLUDES  += -Isrc/common -Isrc/api -Isrc/check -Isrc/delta -Isrc/lz -Isrc/lzma -Isrc/rangecoder -Isrc/simple -Isrc/subblock -Isrc/add_include
  CPPFLAGS  += -MMD $(DEFINES) $(INCLUDES)
  CFLAGS    += $(CPPFLAGS) $(ARCH) -std=c99
  CXXFLAGS  += $(CFLAGS) 
  LDFLAGS   += -s
  LIBS      += 
  RESFLAGS  += $(DEFINES) $(INCLUDES) 
  LDDEPS    += 
  LINKCMD    = $(AR) -rcs $(TARGET) $(OBJECTS)
  define PREBUILDCMDS
  endef
  define PRELINKCMDS
  endef
  define POSTBUILDCMDS
	@echo Running post-build commands
	lib.exe -out:lib/lzma.lib -nologo $(OBJECTS)
  endef
endif

ifeq ($(config),release)
  OBJDIR     = obj/Release
  TARGETDIR  = lib
  TARGET     = $(TARGETDIR)/liblzma.a
  DEFINES   += -DHAVE_CONFIG_H -DHAVE_STDBOOL_H
  INCLUDES  += -Isrc/common -Isrc/api -Isrc/check -Isrc/delta -Isrc/lz -Isrc/lzma -Isrc/rangecoder -Isrc/simple -Isrc/subblock -Isrc/add_include
  CPPFLAGS  += -MMD $(DEFINES) $(INCLUDES)
  CFLAGS    += $(CPPFLAGS) $(ARCH) -std=c99
  CXXFLAGS  += $(CFLAGS) 
  LDFLAGS   += -s
  LIBS      += 
  RESFLAGS  += $(DEFINES) $(INCLUDES) 
  LDDEPS    += 
  LINKCMD    = $(AR) -rcs $(TARGET) $(OBJECTS)
  define PREBUILDCMDS
  endef
  define PRELINKCMDS
  endef
  define POSTBUILDCMDS
	@echo Running post-build commands
	lib.exe -out:lib/lzma.lib -nologo $(OBJECTS)
  endef
endif

OBJECTS := \
	$(OBJDIR)/check.o \
	$(OBJDIR)/crc32_fast.o \
	$(OBJDIR)/crc32_table.o \
	$(OBJDIR)/crc64_fast.o \
	$(OBJDIR)/crc64_table.o \
	$(OBJDIR)/sha256.o \
	$(OBJDIR)/alone_decoder.o \
	$(OBJDIR)/alone_encoder.o \
	$(OBJDIR)/auto_decoder.o \
	$(OBJDIR)/block_buffer_decoder.o \
	$(OBJDIR)/block_buffer_encoder.o \
	$(OBJDIR)/block_decoder.o \
	$(OBJDIR)/block_encoder.o \
	$(OBJDIR)/block_header_decoder.o \
	$(OBJDIR)/block_header_encoder.o \
	$(OBJDIR)/block_util.o \
	$(OBJDIR)/common.o \
	$(OBJDIR)/easy_buffer_encoder.o \
	$(OBJDIR)/easy_decoder_memusage.o \
	$(OBJDIR)/easy_encoder.o \
	$(OBJDIR)/easy_encoder_memusage.o \
	$(OBJDIR)/easy_preset.o \
	$(OBJDIR)/filter_buffer_decoder.o \
	$(OBJDIR)/filter_buffer_encoder.o \
	$(OBJDIR)/filter_common.o \
	$(OBJDIR)/filter_decoder.o \
	$(OBJDIR)/filter_encoder.o \
	$(OBJDIR)/filter_flags_decoder.o \
	$(OBJDIR)/filter_flags_encoder.o \
	$(OBJDIR)/index.o \
	$(OBJDIR)/index_decoder.o \
	$(OBJDIR)/index_encoder.o \
	$(OBJDIR)/index_hash.o \
	$(OBJDIR)/stream_buffer_decoder.o \
	$(OBJDIR)/stream_buffer_encoder.o \
	$(OBJDIR)/stream_decoder.o \
	$(OBJDIR)/stream_encoder.o \
	$(OBJDIR)/stream_flags_common.o \
	$(OBJDIR)/stream_flags_decoder.o \
	$(OBJDIR)/stream_flags_encoder.o \
	$(OBJDIR)/vli_decoder.o \
	$(OBJDIR)/vli_encoder.o \
	$(OBJDIR)/vli_size.o \
	$(OBJDIR)/delta_common.o \
	$(OBJDIR)/delta_decoder.o \
	$(OBJDIR)/delta_encoder.o \
	$(OBJDIR)/lz_decoder.o \
	$(OBJDIR)/lz_encoder.o \
	$(OBJDIR)/lz_encoder_mf.o \
	$(OBJDIR)/fastpos_table.o \
	$(OBJDIR)/lzma2_decoder.o \
	$(OBJDIR)/lzma2_encoder.o \
	$(OBJDIR)/lzma_decoder.o \
	$(OBJDIR)/lzma_encoder.o \
	$(OBJDIR)/lzma_encoder_optimum_fast.o \
	$(OBJDIR)/lzma_encoder_optimum_normal.o \
	$(OBJDIR)/lzma_encoder_presets.o \
	$(OBJDIR)/price_table.o \
	$(OBJDIR)/arm.o \
	$(OBJDIR)/armthumb.o \
	$(OBJDIR)/ia64.o \
	$(OBJDIR)/powerpc.o \
	$(OBJDIR)/simple_coder.o \
	$(OBJDIR)/simple_decoder.o \
	$(OBJDIR)/simple_encoder.o \
	$(OBJDIR)/sparc.o \
	$(OBJDIR)/x86.o \
	$(OBJDIR)/subblock_decoder.o \
	$(OBJDIR)/subblock_decoder_helper.o \
	$(OBJDIR)/subblock_encoder.o \

RESOURCES := \

SHELLTYPE := msdos
ifeq (,$(ComSpec)$(COMSPEC))
  SHELLTYPE := posix
endif
ifeq (/bin,$(findstring /bin,$(SHELL)))
  SHELLTYPE := posix
endif

.PHONY: clean prebuild prelink

all: $(TARGETDIR) $(OBJDIR) prebuild prelink $(TARGET)

$(TARGET): $(GCH) $(OBJECTS) $(LDDEPS) $(RESOURCES)
	@echo Linking lzma
	$(SILENT) $(LINKCMD)
	$(POSTBUILDCMDS)

$(TARGETDIR):
	@echo Creating $(TARGETDIR)
ifeq (posix,$(SHELLTYPE))
	$(SILENT) mkdir -p $(TARGETDIR)
else
	$(SILENT) mkdir $(subst /,\\,$(TARGETDIR))
endif

$(OBJDIR):
	@echo Creating $(OBJDIR)
ifeq (posix,$(SHELLTYPE))
	$(SILENT) mkdir -p $(OBJDIR)
else
	$(SILENT) mkdir $(subst /,\\,$(OBJDIR))
endif

clean:
	@echo Cleaning lzma
ifeq (posix,$(SHELLTYPE))
	$(SILENT) rm -f  $(TARGET)
	$(SILENT) rm -rf $(OBJDIR)
else
	$(SILENT) if exist $(subst /,\\,$(TARGET)) del $(subst /,\\,$(TARGET))
	$(SILENT) if exist $(subst /,\\,$(OBJDIR)) rmdir /s /q $(subst /,\\,$(OBJDIR))
endif

prebuild:
	$(PREBUILDCMDS)

prelink:
	$(PRELINKCMDS)

ifneq (,$(PCH))
$(GCH): $(PCH)
	@echo $(notdir $<)
	$(SILENT) $(CC) $(CFLAGS) -o $@ -c $<
endif

$(OBJDIR)/check.o: src/check/check.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(CFLAGS) -o $@ -c $<
$(OBJDIR)/crc32_fast.o: src/check/crc32_fast.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(CFLAGS) -o $@ -c $<
$(OBJDIR)/crc32_table.o: src/check/crc32_table.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(CFLAGS) -o $@ -c $<
$(OBJDIR)/crc64_fast.o: src/check/crc64_fast.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(CFLAGS) -o $@ -c $<
$(OBJDIR)/crc64_table.o: src/check/crc64_table.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(CFLAGS) -o $@ -c $<
$(OBJDIR)/sha256.o: src/check/sha256.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(CFLAGS) -o $@ -c $<
$(OBJDIR)/alone_decoder.o: src/common/alone_decoder.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(CFLAGS) -o $@ -c $<
$(OBJDIR)/alone_encoder.o: src/common/alone_encoder.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(CFLAGS) -o $@ -c $<
$(OBJDIR)/auto_decoder.o: src/common/auto_decoder.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(CFLAGS) -o $@ -c $<
$(OBJDIR)/block_buffer_decoder.o: src/common/block_buffer_decoder.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(CFLAGS) -o $@ -c $<
$(OBJDIR)/block_buffer_encoder.o: src/common/block_buffer_encoder.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(CFLAGS) -o $@ -c $<
$(OBJDIR)/block_decoder.o: src/common/block_decoder.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(CFLAGS) -o $@ -c $<
$(OBJDIR)/block_encoder.o: src/common/block_encoder.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(CFLAGS) -o $@ -c $<
$(OBJDIR)/block_header_decoder.o: src/common/block_header_decoder.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(CFLAGS) -o $@ -c $<
$(OBJDIR)/block_header_encoder.o: src/common/block_header_encoder.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(CFLAGS) -o $@ -c $<
$(OBJDIR)/block_util.o: src/common/block_util.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(CFLAGS) -o $@ -c $<
$(OBJDIR)/common.o: src/common/common.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(CFLAGS) -o $@ -c $<
$(OBJDIR)/easy_buffer_encoder.o: src/common/easy_buffer_encoder.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(CFLAGS) -o $@ -c $<
$(OBJDIR)/easy_decoder_memusage.o: src/common/easy_decoder_memusage.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(CFLAGS) -o $@ -c $<
$(OBJDIR)/easy_encoder.o: src/common/easy_encoder.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(CFLAGS) -o $@ -c $<
$(OBJDIR)/easy_encoder_memusage.o: src/common/easy_encoder_memusage.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(CFLAGS) -o $@ -c $<
$(OBJDIR)/easy_preset.o: src/common/easy_preset.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(CFLAGS) -o $@ -c $<
$(OBJDIR)/filter_buffer_decoder.o: src/common/filter_buffer_decoder.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(CFLAGS) -o $@ -c $<
$(OBJDIR)/filter_buffer_encoder.o: src/common/filter_buffer_encoder.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(CFLAGS) -o $@ -c $<
$(OBJDIR)/filter_common.o: src/common/filter_common.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(CFLAGS) -o $@ -c $<
$(OBJDIR)/filter_decoder.o: src/common/filter_decoder.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(CFLAGS) -o $@ -c $<
$(OBJDIR)/filter_encoder.o: src/common/filter_encoder.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(CFLAGS) -o $@ -c $<
$(OBJDIR)/filter_flags_decoder.o: src/common/filter_flags_decoder.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(CFLAGS) -o $@ -c $<
$(OBJDIR)/filter_flags_encoder.o: src/common/filter_flags_encoder.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(CFLAGS) -o $@ -c $<
$(OBJDIR)/index.o: src/common/index.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(CFLAGS) -o $@ -c $<
$(OBJDIR)/index_decoder.o: src/common/index_decoder.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(CFLAGS) -o $@ -c $<
$(OBJDIR)/index_encoder.o: src/common/index_encoder.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(CFLAGS) -o $@ -c $<
$(OBJDIR)/index_hash.o: src/common/index_hash.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(CFLAGS) -o $@ -c $<
$(OBJDIR)/stream_buffer_decoder.o: src/common/stream_buffer_decoder.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(CFLAGS) -o $@ -c $<
$(OBJDIR)/stream_buffer_encoder.o: src/common/stream_buffer_encoder.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(CFLAGS) -o $@ -c $<
$(OBJDIR)/stream_decoder.o: src/common/stream_decoder.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(CFLAGS) -o $@ -c $<
$(OBJDIR)/stream_encoder.o: src/common/stream_encoder.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(CFLAGS) -o $@ -c $<
$(OBJDIR)/stream_flags_common.o: src/common/stream_flags_common.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(CFLAGS) -o $@ -c $<
$(OBJDIR)/stream_flags_decoder.o: src/common/stream_flags_decoder.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(CFLAGS) -o $@ -c $<
$(OBJDIR)/stream_flags_encoder.o: src/common/stream_flags_encoder.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(CFLAGS) -o $@ -c $<
$(OBJDIR)/vli_decoder.o: src/common/vli_decoder.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(CFLAGS) -o $@ -c $<
$(OBJDIR)/vli_encoder.o: src/common/vli_encoder.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(CFLAGS) -o $@ -c $<
$(OBJDIR)/vli_size.o: src/common/vli_size.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(CFLAGS) -o $@ -c $<
$(OBJDIR)/delta_common.o: src/delta/delta_common.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(CFLAGS) -o $@ -c $<
$(OBJDIR)/delta_decoder.o: src/delta/delta_decoder.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(CFLAGS) -o $@ -c $<
$(OBJDIR)/delta_encoder.o: src/delta/delta_encoder.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(CFLAGS) -o $@ -c $<
$(OBJDIR)/lz_decoder.o: src/lz/lz_decoder.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(CFLAGS) -o $@ -c $<
$(OBJDIR)/lz_encoder.o: src/lz/lz_encoder.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(CFLAGS) -o $@ -c $<
$(OBJDIR)/lz_encoder_mf.o: src/lz/lz_encoder_mf.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(CFLAGS) -o $@ -c $<
$(OBJDIR)/fastpos_table.o: src/lzma/fastpos_table.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(CFLAGS) -o $@ -c $<
$(OBJDIR)/lzma2_decoder.o: src/lzma/lzma2_decoder.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(CFLAGS) -o $@ -c $<
$(OBJDIR)/lzma2_encoder.o: src/lzma/lzma2_encoder.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(CFLAGS) -o $@ -c $<
$(OBJDIR)/lzma_decoder.o: src/lzma/lzma_decoder.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(CFLAGS) -o $@ -c $<
$(OBJDIR)/lzma_encoder.o: src/lzma/lzma_encoder.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(CFLAGS) -o $@ -c $<
$(OBJDIR)/lzma_encoder_optimum_fast.o: src/lzma/lzma_encoder_optimum_fast.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(CFLAGS) -o $@ -c $<
$(OBJDIR)/lzma_encoder_optimum_normal.o: src/lzma/lzma_encoder_optimum_normal.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(CFLAGS) -o $@ -c $<
$(OBJDIR)/lzma_encoder_presets.o: src/lzma/lzma_encoder_presets.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(CFLAGS) -o $@ -c $<
$(OBJDIR)/price_table.o: src/rangecoder/price_table.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(CFLAGS) -o $@ -c $<
$(OBJDIR)/arm.o: src/simple/arm.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(CFLAGS) -o $@ -c $<
$(OBJDIR)/armthumb.o: src/simple/armthumb.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(CFLAGS) -o $@ -c $<
$(OBJDIR)/ia64.o: src/simple/ia64.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(CFLAGS) -o $@ -c $<
$(OBJDIR)/powerpc.o: src/simple/powerpc.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(CFLAGS) -o $@ -c $<
$(OBJDIR)/simple_coder.o: src/simple/simple_coder.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(CFLAGS) -o $@ -c $<
$(OBJDIR)/simple_decoder.o: src/simple/simple_decoder.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(CFLAGS) -o $@ -c $<
$(OBJDIR)/simple_encoder.o: src/simple/simple_encoder.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(CFLAGS) -o $@ -c $<
$(OBJDIR)/sparc.o: src/simple/sparc.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(CFLAGS) -o $@ -c $<
$(OBJDIR)/x86.o: src/simple/x86.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(CFLAGS) -o $@ -c $<
$(OBJDIR)/subblock_decoder.o: src/subblock/subblock_decoder.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(CFLAGS) -o $@ -c $<
$(OBJDIR)/subblock_decoder_helper.o: src/subblock/subblock_decoder_helper.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(CFLAGS) -o $@ -c $<
$(OBJDIR)/subblock_encoder.o: src/subblock/subblock_encoder.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(CFLAGS) -o $@ -c $<

-include $(OBJECTS:%.o=%.d)
