# GNU Make solution makefile autogenerated by Premake
# Usage: make [ config=config_name ]
# Where {config_name} is one of: "debug", "release".

ifndef config
  config=debug
endif
export config

PROJECTS := lzma

.PHONY: all clean $(PROJECTS)

all: $(PROJECTS)

lzma: 
	@echo ==== Building lzma ====
	@${MAKE} --no-print-directory -C . -f lzma.make

clean:
	@${MAKE} --no-print-directory -C . -f lzma.make clean

